powa/query.py
We need to join on powa_statements with both queryid and dbid.
For queries on system objects, the queryid will be the same across databases.
Should fix #15 .
=> Fix wrong counts in query details for queries on system objects

powa/query.py
Hello Dalibo team
This pull request fixe "TypeError: 'dict' object does not support indexing" error by adding call text function from sqlalchemy.
This error occurs when the powa-web application explains a query with like statement '%'.
=> Fixe explain query with like statement

powa/static/js/powa/utils/duration.js
The isAfter function seems to only compare up to milliseconds so we have
to manually compare for more precision if m1 and m2 seem equal.
The calculation for microsecDiff was inverted.
Should fix dalibo/powa#88 .
=> Fix wrong calculation of microseconds difference

powa/ui_methods.py
We most probably don't want the `username` as id for an input field.
=> Fix broken usage of label for fields

powa/static/css/powa-all.min.css, powa/static/scss/powa.scss, powa/templates/database/query/detail.html
Layout improvements for the query detail page.
- Smaller font for the SQL block,
- Max height set with scrollbar if required,
- Below info centered.
Before:
After:
=> Query detail

powa/templates/layout.html
Fixes #35
We don't use fontawesome and unfortunately there's no bug icon in foundation icons set.
Let's remove it.
=> Remove invisible bug icon

powa/query.py
This PR fix disk hit ratio chart (missing `* 100` factor)
Before:
After:
=> Fix disk hit ratio

powa/templates/layout.html
Avoids horizontal scroll bar to appear in most cases
Please note that it can be seen in the configuration page easily. There's still a problem with the horizontal scroll bar in some other pages. I'm currently diggin into it.
=> Prevent footer to be too wide

powa/framework.py
~~Remove unnecessary check for srvid=0. Alias is automatically added during first insert in power-archivist.~~ => Only change the query to use alias instead of hostname:port
=> Use alias instead of hostname:port

powa/server.py
The missing join condition resulted in incorrect numbers of queries, runtime, page faults, context switches, and block access per second.
The above numbers were N times bigger, where N is the number of databases in the cluster with some registered activity.
=> Fix global databases metrics query

powa/collector.py
Potentially it could lead to sql injection, although chances that it will be exploited are close to zero due to the url format validation.
=> Remove useless string formatting

powa/database.py, powa/query.py, powa/server.py
The goal was to remove zero values.
However "c.calls is not None" was translated to "WHERE true"
and "c.calls != None" to "WHERE c.calls IS NOT NULL".
Fix #102
=> Fix generated where clause on c.calls.

powa/database.py, powa/server.py
The last value computed is equal to 0 and can break graph:
Before:
After:
=> Last mesure_interval must be ignored.

powa/qual.py
`stmt` was missing and leads sqlalchemy to add a join on powa_statement without filtering clause.
It generates a cartesian product and python eating all memory.
Thanks @rdunklau for the fix!
=> Avoid cartesian product in predicate view

powa/dashboards.py, powa/database.py, powa/query.py, powa/server.py
Currently all link in powa-web to the documentation are broken and leading in a 404.
*Example:*
https://powa.readthedocs.io/en/latest/stats_extensions/pg_wait_sampling.html
*Should be:*
https://powa.readthedocs.io/en/latest/components/stats_extensions/pg_wait_sampling.html
=> Fixed links to documentation

powa/database.py, powa/query.py, powa/server.py
Just a very small UI change...maybe it's just me, but I prefer to strip the decimal places for plain integers, like amouts/counts.
Example from the demo, where you can see the ".00" in the "#" column:
Would then look like:
Internally the IntegerCell is exending the NumberCell and just setting decimals to 0
=> Changed some "number" table columns to "integer"

powa/templates/layout.html
The web UI still shows a copyright to 2019. Update it to 2020.
=> Update copyright to 2020

powa/database.py, powa/query.py
Several queries are built from powa_get<something>data_detailed_db by
passing srvid. Later we join with powa_statements but join on srvid was
missing which often lead to a seqscan on powa_statements.
Thanks to join on srvid we can use powa_statements PK.
=> Add join clause on srvid when joining with powa_statements.

powa/templates/layout.html, powa/ui_methods.py
Hi,
I noticed that the copyright statement at the bottom is still saying 2020. This PR fixes that by just showing the current year, which has the benefit of no further work in upcoming years.
Cheers,
Christoph
=> Fix copyright year in footer

powa/templates/login.html
The server dropdown on login page is sorted by the whole text.
In a huge postgres environment it is usefull to search for server and clusters (and project). 
To have this info available for each entry you have to concat it like "project1, cluster1, server1", "project1, cluster2, server2", "project2, cluster3, server3" ...
The serverlist is sorted by the text of the entries, so it is not easy to find entries by a text which is in the middle of the entries.
All common browsers suport the tag "**datalist**". Together with "**input**" this provides an autocomplete, so you can start typing a word and the option list will contain only the entries mathci with the typed word.
Using this approach the login on huge environments is much more easy.
=> login serverlist with <datalist>...</datalist>

powa/static/js/powa/models/Wizard.js
Previous change 291a34d2ecbd67d4e40e1055b873f6f3b9ba8325 was not doing anything actually.
=> wizard: effectively merge nodes with same qualid

powa/io_template.py
Follow up for 33d71a55f4daf2ed95f4
=> Fix wrong return type for GlobalIoMetricGroup._get_metrics

powa/static/styles/main.scss
As sugested in https://github.com/vuetifyjs/vuetify/issues/12229#issuecomment-888484775 It's solved in vuetify3.
=> Fix svg not displayed in Graph title on firefox

powa/static/js/components/dynamic/Wizard.vue
This fixes an JS error when no access method can be found.
It also fixes a display bug in case of unmanaged quals in the unoptimized quals grid.
=> Wizard unoptmized quals

powa/database.py, powa/server.py, powa/static/js/components/dynamic/Grid.vue
Previously we were expecting the first column not to be provided and to be taken into account in the UI. We now explicitely set it server side.
=> Make sure toprow headers count match columns for grid

.git-blame-ignore-revs
It for now only contains the latest commit reference, which modified a lot of lines without any functional change.
There might be some existing commit that would benefit from being in this file too, but it will be taken care of later if that's the case.
=> Introduce a .git-blame-ignore-revs file

setup.py
After the commit ecb8013b5f in which we changed the way the python code is formatted, the "hack" to get the version in setup.py no longer worked.
The current commit fixes this. A better management of the version should be implemented. For example, using setuptools_scm could be a good option.
Related to #218
=> Fix version error message when building package

powa/static/js/utils/sql.js
For example, with the following query the SQL formatter / highlighter raises an error:
``` SQL
SELECT id AS srvid,
CASE WHEN id = $1 THEN
$2
ELSE
COALESCE(alias, hostname || $3 || port)
END AS alias,
CASE WHEN id = $4 THEN $5 ELSE hostname END as hostname,
CASE WHEN id = $6 THEN $7 ELSE port END AS port,
CASE WHEN id = $8 THEN set.setting
ELSE s.version::text
END AS version
FROM public.powa_servers s
LEFT JOIN pg_settings set ON set.name = $9
AND s.id = $10
```
Until this can be fixed in the library and in order to prevent PoWA to work improperly (navigation broken), we catch the error and show the unhighlighted value.
=> Don't fail on SQL format errors

package-lock.json, package.json, powa/static/js/utils/sql.js
As mention in https://github.com/powa-team/powa-web/pull/227#issuecomment-2475746550, the `sql-formatter` doesn't correctly handles reserved keywords when they are used as alias for tables.
After some searching I found an other library which seem to be more popular and doesn't fail when formatting such queries.
=> Change SQL formatter library

powa/dashboards.py
Postgres 13 or lower don't have predefined roles, so we call unnest on an empty python array which is emitted as '{}'.  This is ambiguous for postgres so we need to explicitly cast the value as an array of text, which works for both an empty array and a non empty array (which is emitted as ARRAY[...]).
=> fix: Fix notifiation authorization check on pg13-

powa/server.py
On older postgres version the existing cast to numeric isn't enough to guarantee that the result expression is numeric too, so explicitly cast the resulting expression to numeric to make sure that we can round the result.
=> fix: Fix pg_stat_archiver on pg13-

RELEASE.md
The existing instructions were entirely ignoring the python part of powa-web.
While at it make the changed file list formatting consistent.
=> fix: Update the release instructions

.ruff.toml, powa-web, powa/powa.wsgi
powa-web and powa.wsgi were not checked by Ruff because the extension for those files don't match default inclusions.
=> Format more files with Ruff

.husky/pre-commit, package-lock.json, package.json
=> Husky removal

powa/query.py, powa/server.py
PR sacrifice on the altar of the linting gods
=> Make ruff happy

powa/sql/views_grid.py
After discussion with @rjuju , these IN are not necessary, they may even be harmful.
As they use CPU cycles, let's remove them
=> Remove not necessary joins on powa_statements

powa/sql/views_grid.py
There is a bug: the result is still ok, but it's a performance issue
The left boundary query for powa_base_waitdata_detailed_db on the interval is wrong: the matching interval should be from/from (see other queries that do the same manipulation). So we're doing twice the full interval of the query, once for nothing (and we redo the comparisons on the unnested records on this large one, which takes lots of cpu)
=> Improve powa_wait_sampling_history query

powa/dashboards.py, powa/database.py, powa/server.py, powa/static/js/components/dynamic/Graph.vue
Graph() accepts a new optional "desc" parameter.  If provided, it will be included in the hover help before the per-metric description.
As an example, the "Backend age" graphs now mention that autovacuum worker are included in the graph as this should be modified soon.
=> Add a new optional graph description

powa/sql/views_graph.py, powa/sql/views_grid.py
The catalog tables are not refreshed very often (the default is every month), so we shouldn't rely on them when displaying information that doesn't also come from the catalogs.
=> Rely on powa_databases rather than powa_catalog_databases

powa/database.py, powa/server.py, powa/sql/views_graph.py
I think it makes sense to keep them only on the vacuum graphs (database objects view)
Without this, we get very long "transactions" and xids displayed in the main graph, and it's confusing
=> Do not display autovacuum workers in the sessions graphs

powa/sql/views_graph.py
It wrongly computes the sampling: the "total" column is not correct in this context: we (most of the time) have more than 1 record per sample. If you have 100 sessions, the sampling will be off by a factor of 100, and you'll end up with only 1 sample
It's a bit ugly to fix, because we need another subquery...
Closes #254
=> Fix the sampling of the pgsa query

run_powa.py
This script is only meant for development, but it's still confusing that it ignores the configured listening address and port especially especially since needing different values than the hardcoded ones is a common need.
=> Support dynamic address and port un run_powa.py

powa/framework.py
If the powa-extension is not installed on the repository server, login should fail and the UI should report an error message.  Unfortunately the existing logic was broken as the underlying function was throwing an exception rather than returning an expected None if the powa extension is not installed.  This commit fixes this case and properly return None.
While at it, report a better error if one of the needed extension is not installed on the repository server.  An internal error stack is still displayed, but at least it will show an informative "extenion not found" with the associated extension name rather than an obscure "key error" message.
=> Properly detect missing extensions

powa/sql/views_graph.py
powa-archivist 3.1.0 added a new "clocl_ts" column in the pg_stat_activity related tables, to compute more precise age metrics.  There is no guarantee that this column is valued if the extension was just upgraded, so fallback on the previous "ts" column when needed.
=> Use the newly introduced "clock_ts" column
