powa-team/powa-web

- powa/templates/login.html
We are starting to use powa with >1000 servers and the unsorted list of hostnames is an issue for us.
We would be really happy if this one liner could get merged.
> Show a sorted list of servers on login screen

- powa/static/css/powa-all.min.css
This needs update because the recent change of sass compiler introduces
changes in floating number rounding
Follow up for 9fd53b5e84
> Update compiled css

- package.json
- powa/static/css/powa-all.min.css
- updates grunt-sass to the latest version along with generated css modifications,
- prevents unintended grunt-sass updates in the future.
> Set grunt-sass version

- powa/templates/login.html
Only costmetics.
Before:
After:
> Better layout for login page

- powa/config.py
- powa/static/css/powa-all.min.css
- powa/static/scss/powa.scss
Only "green" texts should be clickable.
> Only links are green

- powa/static/css/powa-all.min.css
- powa/static/scss/powa_backgrid.scss
> Correctly align 'no data' in grid tables

- powa/config.py
> Shorten headers in extensions grid

- powa/dashboards.py
- powa/qual.py
- powa/query.py
- powa/sql/__init__.py
- powa/sql/views.py
- powa/templates/database/query/qualdetail.html
Small fixes regarding multiple user and performance problems with quals.
> Multiuser fixes

- powa/sql/views.py
This PR bring following changes:
- Change the predicate order:
`WHERE tstzrange(:from, :to, '[]') @> (records).ts`
to
`WHERE (records).ts <@ tstzrange(:from, :to, '[]')`
I think it is more clear, it is like using:
`WHERE col1 = 4`
instead of
`WHERE 4 = col1`
- Remove an unecessary `UNION ALL` and computation with `min_ts` and `max_ts` : this solved display issue with database object tab. I don't know only this tab was impacted.
Before: https://demo-powa.anayrat.info/server/2/overview/?from=2019-11-26T19%3A46%3A50%2B01%3A00&to=2019-11-27T19%3A46%3A50%2B01%3A00
After:
https://dev-powa.anayrat.info/server/2/overview/?from=2019-11-26T19%3A45%3A46%2B01%3A00&to=2019-11-27T19%3A45%3A46%2B01%3A00
- Comment some parts of the queries
Note there is still an issue with "general overview":
When you …
> Rework queries

- powa/sql/views.py
This allows to use indexes to perform the join instead of joining
and filter after.
Before:
```
>  Nested Loop Semi Join  (cost=0.41..6217.26 rows=1 width=553) (actual time=119.577..19930.485 rows=376 loops=3)
Join Filter: (psh.queryid = powa_statements_1.queryid)
Rows Removed by Join Filter: 3280129
Buffers: shared hit=3125260
->  Index Scan using powa_statements_history_query_ts on powa_statements_history psh  (cost=0.41..8.43 rows=1 width=553) (actual time=78.585..123.357 rows=376 loops=3)
Index Cond: ((srvid = 14) AND (coalesce_range && '["2020-07-01 07:41:27+00","2020-07-01 18:07:16+00"]'::tstzrange))
Filter: (dbid = powa_databases.oid)
Rows Removed by Filter: 9386
Buffers: shared hit=31758
->  Seq Scan on powa_statements powa_statements_1  (cost=0.00..6129.54 rows=6343 width=8) …
```
> Add clause on srvid

- powa/config.py
> Add powa_coaslesce setting on config page.

- powa/qual.py
- powa/server.py
- powa/sql/__init__.py
Should fix  #108
As here, fix missing simple quote.
Thanks @rjuju
> Push qualid and queryid into subquery

- CHANGELOG
- powa/__init__.py
- powa/config.py
- powa/dashboards.py
- powa/database.py
- powa/framework.py
- powa/overview.py
- powa/query.py
- powa/server.py
- powa/sql/__init__.py
- powa/sql/views.py
- powa/wizard.py
See also powa-archivist - https://github.com/powa-team/powa-archivist/pull/36
> Add compatibility with pgss 1.8

- powa/framework.py
I added a fixup commit for the removal of SQLAlchemy dependency.
> fixup! Remove sqlalchemy dependency.

- package-lock.json
- package.json
> V5 compatibility with Node 22

- powa/static/styles/main.scss
> Fix glitch in top row header in Grid component

- .github/workflows/javascript.yml
- vite.config.js
Checks are now also done on CI.
> Fix wrong package name in vite config for building chunks

- powa/static/js/composables/DateRangeService.js
> Always use end of time unit for "to" date in range

- powa/database.py
- powa/server.py
It didn't take into account whether the session was idle, so it was inaccurate
Also add some workaround for issue https://github.com/powa-team/powa-archivist/issues/98 until the archivist is fixed
> Fix the oldest query display

- powa/sql/views_graph.py
On many queries, counters are multiplied by the number of replicas...
> missing srvid on joins on powa_catalog_databases

- powa/static/js/components/LoginView.vue
> Allow autocomplete for server name selector in login view

- powa/static/js/components/dynamic/Graph.vue
- powa/static/js/stores/dashboard.js
And show the same line (sync) on other graphs on the same page.
Fixes #275
> Show cursor position on graphs
